from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="index.html"),
    path('aboutt',views.about,name="about.html"),
    path('blog',views.blog,name="blog.html"),
    path('blogg',views.blog_single,name="blog-single.html"),
    path('checkout.html',views.chekout,name="checkout.html"),
    path('contact',views.contact,name="contact.html"),
    path('faqs',views.faqs,name="faqs.html"),
    path('help',views.help,name="help.html"),
    path('payment',views.payment,name="payment.html"),
    path('privacy',views.privacy,name="privacy.html"),
    path('product',views.product,name="product.html"),
    path('product2',views.product2,name="product2.html"),
    path('single',views.single,name="single.html"),
    path('singlee',views.singlee,name="single2.html"),
    path('terms',views.termas,name="terms.html"),
    path('regi',views.register,name="regi"),
    path('hilogin',views.logincheck,name="hilogin"),
    path('out',views.logout,name="out"),
    path('product3',views.product3,name="product3.html"),
    path('mi',views.miband,name="miband.html"),
    path('mitv',views.mi4tv,name="mi4tv.html"),
    path("tabwatch",views.tabandwatch,name="tabandwatch.html"),
    path("leptop",views.pro,name="lep.html"),
    path("tv",views.tv,name="tv.html"),
    path("lg32inch",views.lg32inch,name="lg32inch.html"),
    path("complaints",views.complaint,name="complaints.html"),
    path("fariyad",views.com,name="fariyad"),
    path("ac",views.ac,name="ac.html"),
    path("connect",views.connect,name="connect"),
    path('addtocart/<int:id>',views.addtocart,name='addtocart'),
    path('destroycart/<int:id>',views.destroycart,name='checkout.html'),
    path('registerrr',views.registerrr,name='registerrr'),
    path('finalregister',views.registerrr,name='finalregister'),
    path('singleproduct/<int:id>',views.singleproduct,name="singleproduct"),
    path('login',views.finallogin,name="login"),
    path('heylogin',views.loginform,name="heylogin"),
    path('user',views.profile,name="profile.html"),
    path('feedbackkk',views.feedbackview,name="single.html"),
    path('update/<int:id>',views.update,name='update'),
    path('inquiry',views.inquery,name="inquiry.html"),
    path('inq',views.inquery,name='inq'),
    path("feeddata",views.feedbackview,name="feeddata"),
    path("orderurl",views.orders,name="order.html"),
    path("placeorder/<int:id>",views.placeorder,name="placeorder"),
    path("ree",views.re,name="re.html"),
    path('reporttt',views.reportstock,name="report.html"),
    path('stockreport/<int:id>',views.stockreport,name="stockreport"),
    path('categoryreport',views.reportcategory,name="categoryreport"),
    path('inqueryreport',views.reportinquery,name="inqueryreport"),
    path('feedbackreport',views.reportfeedback,name="feedbackreport"),
    path('reportorder',views.reportorder,name="reportorder"),
    path('orderdetails/<int:id>',views.orderdetails,name='orderdetails.html'),
    path('forgot', views.forgot, name='forgot.html'),
    path('forgotpassword', views.forgotpassword, name='forgotpassword'),
    path('changepass',views.changep,name="changepass.html"),
    path('invoice/<int:id>',views.invoice,name="invoice.html"),
    path('cancelorder/<int:id>',views.cancelorder,name="order.html"),

]