# Generated by Django 4.1.3 on 2023-01-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpassword',
            field=models.IntegerField(null=True),
        ),
    ]
