# Generated by Django 4.1.3 on 2023-01-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Image',
        ),
    ]
