# Generated by Django 4.1.3 on 2023-01-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
