# Generated by Django 4.1.3 on 2023-01-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_image_path_alter_image_image_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
