# Generated by Django 4.1.3 on 2023-01-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliant',
            name='compliant_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='compliant',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
