# Generated by Django 4.1.3 on 2023-01-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_compliant_compliant_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliant',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='compliant',
            name='compliant_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='compliant',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
