# Generated by Django 4.1.3 on 2023-01-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_compliant_product_id_alter_compliant_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliant_details', models.TextField()),
            ],
        ),
    ]
