# Generated by Django 4.1.3 on 2023-01-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_commm'),
    ]

    operations = [
        migrations.CreateModel(
            name='connectus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject_here', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
