# Generated by Django 4.1.3 on 2023-01-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_cartfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_status',
            field=models.IntegerField(null=True),
        ),
    ]
