# Generated by Django 4.1.3 on 2023-02-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image2',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
