# Generated by Django 4.1.3 on 2023-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquery',
            name='inquery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inquery',
            name='response',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
