# Generated by Django 4.1.3 on 2023-02-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_feedback_product_id_feedback_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
