# Generated by Django 4.1.5 on 2023-02-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_cart_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
