# Generated by Django 4.1 on 2023-02-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_cart_totalprice_alter_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Famale', 'Famale')], max_length=30),
        ),
    ]
