# Generated by Django 4.1 on 2023-02-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
    ]
