# Generated by Django 4.1 on 2023-02-10 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_user_password_alter_user_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_name',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
