# Generated by Django 4.0.5 on 2023-02-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_order_details_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commm',
            new_name='Complaints',
        ),
    ]
