# Generated by Django 4.0.5 on 2023-02-27 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_commm_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
